services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${OVERRIDE_HOSTNAME}  
    domainname: ${DMS_DOMAIN}      
    env_file: .env                  
    ports:
      - "25:25"                     
      - "465:465"                 
      - "143:143"                  
      - "993:993"                  
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config:/tmp/docker-mailserver
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    depends_on:
      - mailserver
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=${ROUNDCUBEMAIL_DEFAULT_HOST}
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBEMAIL_IMAP_SERVER=${ROUNDCUBEMAIL_IMAP_SERVER}
    ports:
      - "8888:80"
    volumes:
      - ./roundcube/config:/var/www/html/config
    restart: unless-stopped
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: email-api
    ports:
      - "5587:3000"
    volumes:
      - ./config:/config
       - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - mailserver
    restart: unless-stopped

